# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Keychain Demo App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Locksmith'
	pod 'SwiftKeychainWrapper'

  # Pods for Keychain Demo App

end
